[package]
name = "event-query"
version = "0.1.0"
edition = "2021"

[lib]
name = "event_executed_query"
crate-type = ["cdylib", "rlib"]

[dependencies]
shared = { path = "../shared" }
serde_json = { workspace = true }
