name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type: bug", "priority: medium"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Start the application with `cargo run`
        2. Send a Ray event with specific payload
        3. Observe the behavior
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide environment details
      value: |
        - **OS**: macOS [version]
        - **Rust version**: `rustc --version`
        - **Application version**: [commit hash or tag]
        - **Ray PHP version**: [if applicable]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages & Logs
      description: Any error messages, stack traces, or relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience, workaround available
        - Medium - Affects functionality, no workaround
        - High - Breaks core functionality
        - Critical - Application crashes or data loss
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute a fix?
      options:
        - label: I would like to work on fixing this bug
        - label: I can provide additional testing or information